version: "3.9"

services:
  user_balance_backend:
    container_name: user_balance_backend
    restart: always
    build:
      context: ..
      dockerfile: build/Dockerfile
    entrypoint: /entrypoint.sh
    ports:
      - "8001:8001"
    env_file:
      - ../environments/.env.local
    depends_on:
      - user_balance_db
    networks:
      - deploy_zimran_network

  user_balance_db:
    container_name: user_balance_db
    restart: always
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - balance_db_data:/var/lib/postgresql/data
    networks:
      - deploy_zimran_network


volumes:
  balance_db_data:

networks:
  deploy_zimran_network:
    external: true